export const assets = {
  adaptive_treshold_lena_test: '/base/test/assets/adaptive_treshold_lena_test.png',
  card: 'base/test/assets/card.png',
  haar_test_100: 'base/test/assets/haar_test_100.png',
  haar_test_200: 'base/test/assets/haar_test_200.png',
  haar_test_300: 'base/test/assets/haar_test_300.png',
  lena_grayscaled: 'base/test/assets/lena_grayscaled.png',
  lena_raw: 'base/test/assets/lena_raw.json',
  lena: 'base/test/assets/lena.png',
  morphology_blackhat_custom_kernel: 'base/test/assets/morphology_blackhat_custom_kernel.png',
  morphology_blackhat: 'base/test/assets/morphology_blackhat.png',
  morphology_close_custom_kernel: 'base/test/assets/morphology_close_custom_kernel.png',
  morphology_close: 'base/test/assets/morphology_close.png',
  morphology_dilated_custom_kernel: 'base/test/assets/morphology_dilated_custom_kernel.png',
  morphology_dilated: 'base/test/assets/morphology_dilated.png',
  morphology_eroded_custom_kernel: 'base/test/assets/morphology_eroded_custom_kernel.png',
  morphology_eroded: 'base/test/assets/morphology_eroded.png',
  morphology_gradient_custom_kernel: 'base/test/assets/morphology_gradient_custom_kernel.png',
  morphology_gradient: 'base/test/assets/morphology_gradient.png',
  morphology_open_custom_kernel: 'base/test/assets/morphology_open_custom_kernel.png',
  morphology_open: 'base/test/assets/morphology_open.png',
  morphology_src: 'base/test/assets/morphology_src.png',
  morphology_tophat_custom_kernel: 'base/test/assets/morphology_tophat_custom_kernel.png',
  morphology_tophat: 'base/test/assets/morphology_tophat.png',
  upsample_result: 'base/test/assets/upsample_result.png',
  v_red_blue: 'base/test/assets/v_red_blue.png',
  v_white_black: 'base/test/assets/v_white_black.png',
  video_mp4: 'base/test/assets/video.mp4',
  video_ogg: 'base/test/assets/video.ogg',
  white_black: 'base/test/assets/white_black.png  ',
};
